core/urls.py
from django.urls import path
from.import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about-company/', views.about_Company, name='about-company'),
]

glowhiteherbals/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve


admin.site.site_header  =  "GloWhite Herbals Admin Panel"  
admin.site.site_title  =  "GloWhiteHerbals"
admin.site.index_title  =  ""
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('store/',include('store.urls')),
    path('accounts/',include('accounts.urls')),
    re_path (r'^media/(?P<path>.*)$', serve ,{'document_root' : settings.MEDIA_ROOT } ) ,
    
]
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from PIL import Image

# Create your models here.
class Carousel(models.Model):
    carousel_title       = models.CharField(max_length=255, blank=True, null=True)
    carousel_description = models.TextField(blank=True, null=True)
    carousel_image       = models.ImageField(upload_to='photos/carouselImage')
    

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        imag = Image.open(self.carousel_image.path)
        output_size = (1280, 720,)
        newSize = imag.resize(output_size,Image.BICUBIC)
        newSize.format = 'PNG'
        newSize.save(self.carousel_image.path,quality=95)

    def __str__(self):
        return str(self.carousel_title)
    class Meta:
        verbose_name_plural = 'Sliders'

    

store/models.py
from django.db import models
from category.models import Category,SubCategory
from django.urls import reverse
from PIL import Image
from accounts.models import User
from django.db.models import Avg
# Create your models here.

class Product(models.Model):
    category            = models.ForeignKey(Category, on_delete=models.CASCADE)
    subCategory         = models.ForeignKey(SubCategory, on_delete=models.CASCADE,blank=True, null=True)
    product_name        = models.CharField(max_length=255)
    slug                = models.SlugField(max_length = 200, unique = True)
    product_tagline     = models.CharField(max_length=1000,blank=True, null=True)
    product_description = models.TextField()
    price               = models.IntegerField()
    discounted_price    = models.IntegerField(blank=True)
    ingredients         = models.CharField(max_length=1000, blank=True, null=True)
    Product_image       = models.ImageField(upload_to='photos/products')
    image_gallery_1     = models.ImageField(upload_to='photos/products', blank=True, null=True)
    image_gallery_2     = models.ImageField(upload_to='photos/products', blank=True, null=True)
    image_gallery_3     = models.ImageField(upload_to='photos/products', blank=True, null=True)
    image_gallery_4     = models.ImageField(upload_to='photos/products', blank=True, null=True)
    quantity            = models.CharField(max_length=20,blank=True)
    Product_feature1    = models.CharField(max_length=150,blank=True)
    Product_feature2    = models.CharField(max_length=150,blank=True)
    Product_feature3    = models.CharField(max_length=150,blank=True)
    Product_feature4    = models.CharField(max_length=150,blank=True)
    Product_feature5    = models.CharField(max_length=150,blank=True)
    Product_feature6    = models.CharField(max_length=150,blank=True)
    Product_feature7    = models.CharField(max_length=150,blank=True)
    url                 = models.URLField(blank=True,null=True)
    is_available        = models.BooleanField(default=True)
    created_date        = models.DateTimeField(auto_now_add=True)
    modified_date       = models.DateTimeField(auto_now=True ,)


    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        imag = Image.open(self.Product_image.path)
        output_size = (650, 650,)
        newSize = imag.resize(output_size,Image.BICUBIC)
        newSize.format = 'PNG'
        newSize.save(self.Product_image.path,quality=95)


    def __str__(self):
        return self.product_name

    def product_url(self):
        return reverse('product_detail',args=[self.category.slug, self.slug])

    def avg_rate(self):
        review = Review.objects.filter(product=self).aggregate(avarage=Avg('rating'))
        avg=0
        if review["avarage"] is not None:
            avg=float(review["avarage"])
        return format(avg,'.2f')



class Review(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    product  = models.ForeignKey(Product,on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
   
    rating = models.FloatField()
    subject = models.CharField(max_length=70,blank=True,null=True)
    reveiw = models.TextField(max_length=200,blank=True,null=True)
    ip = models.CharField(max_length=200)

    status = models.BooleanField(default=True)
    
    def __str__(self):
        return self.user.username

core/views.py
from django.http.response import HttpResponse
from django.shortcuts import render
from .models import Carousel
from category.models import Category
from store.models import Product
# Create your views here.

def home(request):
    carousel = Carousel.objects.all().order_by('-id')
    facial_kits = Category.objects.filter(category_name__icontains = 'facial kits')
    bleaches = Category.objects.filter(category_name__icontains = 'bleaches')

    featured_products = Product.objects.all().order_by('modified_date')[1::5]
    context={
        'carousel':carousel,
        'facial_kits':facial_kits,
        'bleaches':bleaches,
        'featured_products':featured_products,
    }
    return render(request, 'core/home.html',context)


def about_Company(request):
    return render(request, 'core/about.html')

core/templates/core/about.html
{% extends 'core/base.html' %}
{% load static %}
{% block css %} {{ block.super }}
    <link rel="stylesheet" href="{% static 'core/css/about.css' %}">
{% endblock css %}

{% block content %}

  <section class="about_us">
    <div class="container">
      <div class="about_us_content">
        <h1 class="fw-bold ">About The Company</h1>
        <p> <b class="text-dark">GloWhite Herbals</b> Based in Kolkata, it was Established in 1997, as a Salon Eco Products Manufacturer. That time
          we are among the very few skin care Manufacturers based in India. A little start Goes big as we are currently 
          serving more than 2.5 million salons in South India. </p>
          <p>
          We have worked with the best <b class="text-dark">Dermatologists</b> to formulate our products and produce what we do the best we at.
          GloWhite Herbals ARE Dedicated toward producing skin care that REALLY works! skin care that is Effective and
          is gentle on skin. All of our products are produced in a healthy environment and are Researched and developed
          By Highly experienced Dermatologists.
        </p>
      </div>
    </div>
  </section>

{% endblock content %}

core/templates/core/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="{{ml.meta_title}} ">
    <meta name="description" content="{{ml.meta_description}}">
    <link rel="icon" type="image" href="{% static 'core/images/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}">
  
    {% block css %}
    <link rel="stylesheet" href="{% static 'core/css/base.css' %}" />
    {% endblock css %}
   
   
   
    <title>
    {% block title %}
       GloWhite Herbals
    {% endblock title %}
    </title>
  </head>
  <body>
   

{% include 'core/includes/navbar.html' %}


  <!--***************************  -->
  {% block content %}
 
  {% endblock content %}
  
 
{% include 'core/includes/footer.html' %}
  
  <!-- END OF FOOTER -->
  <script src="js/bootstrap.js"></script>
  
</body>

</html>

<script src="{% static 'core/js/bootstrap.js' %}"></script>
  </body>
</html>

core/templates/core/home.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{{ block.super }}{% endblock title %}

{% block css %}{{ block.super }}
<link rel="stylesheet" href="{% static 'core/css/home.css' %}">
{% endblock css %}

{% block content %}

 <section class="home overflow-hidden pt-1 shadow-lg">
    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
     {% for indicator in carousel %}
          {% if forloop.first %}
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="{{forloop.counter0}}" class="active"
          aria-current="true" aria-label="Slide 1"></button>
          {% else %}
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="{{forloop.counter0}}"
          aria-label="Slide 2"></button>
          {% endif %}
     {% endfor %}
       
      </div> 

      <div class="carousel-inner">
      {% for slider in carousel %}
        <div class="carousel-item {% if forloop.first %}active{% endif %}" data-bs-interval="2500">
          <img src="{{slider.carousel_image.url}}" class="d-block img-fluid w-100" alt="unable load Image">
        </div>
       {% endfor %}
       
     
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
        data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true">
          <span class=" ti-angle-left slider-icon">
             < </span>
        </span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
        data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true">
          <span class=" ti-angle-right slider-icon"> > </span>

        </span>
        <span class="visually-hidden"></span>
      </button>
    </div>
  </section>
  <!--***************************  -->

  
  <section id="products" class="products mt-lg-5 pt-2">
    <div class="container">
      <div class="row gy-2">
      {% for facial in facial_kits %}
        <div class="col-12 col-md-12 col-lg-6 col-xl-6 p-0">
          <div class="about_product_item">
            <h4 class="text-uppercase"></h4>
            <h2 class="text-uppercase">{{facial.category_short_intro}}</h2>
            <p class="decs">{{facial.description|linebreaks}}</p>
          </div>
        </div>
        <div class="col-12 col-md-12 col-lg-6 col-xl-6">
		<a href="{% url 'products_by_category' facial.slug %}">
		 <div class="product_item_images">
            <div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel">
              <div class="carousel-inner">          
			 {% if facial.product_set.all %}
				{% for pro_img in facial.product_set.all %}
					<div class="carousel-item {% if forloop.first %}active{% endif %}" data-bs-interval="1500">
						<img src="{{pro_img.Product_image.url}}" class="d-block img-fluid w-100 rounded" alt="unable load Image">
					</div>
				{% endfor %}
			{% endif %}
              </div>
            </div>
          </div>
		  </a>
        </div>

{% endfor %}
      </div>
    </div>
  </section>

  <div class="Spotlights mt-5">
    <h2 class="text-center text-capitalize mb-5 ">In The SpotLights</h2>

    <div class="container-fluid px-lg-5 m-lg-4 overflow-hidden mb-5">
      <div class="row gx-md-4 gx-lg-5 gy-4 gy-md-4 gy-lg-4 text-center justify-content-center ">
    {% for category in links %}
	  {% if category.image1 %}
        <div class="col-12 col-md-4 col-lg-4 spotlight_box">
          <a href="{% url 'products_by_category' category.slug %}">
            <div class="spotlights_item overflow-hidden">
			
              <img src="{{category.image1.url}}" alt="" class="img-fluid bg-body">
          
			</div>
            <div class="about_spotlights_item">
              <p class="text-center">{{category.category_name}}</p>
            </div>
          </a>
        </div>
	  {% endif %}
    {% endfor %}

      </div>
    </div>
  </div>

<section class="m-2 mb-5">
  <div class="container">

    <div class="row gy-2">
      {% for bleach in bleaches %}
        <div class="col-12 col-md-12 col-lg-6 col-xl-6 p-0">
          <div class="about_product_item">
            <h4 class="text-uppercase">{{bleach.category_tagline}}</h4>
            <h2 class="text-uppercase">{{bleach.category_short_intro}}</h2>
            <p class="decs">{{bleach.description}}</p>
          </div>
        </div>


        <div class="col-12 col-md-12 col-lg-6 col-xl-6 mt-5">
		<a href="{% url 'products_by_category' bleach.slug %}">
		 <div class="product_item_images">
            <div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel">
              <div class="carousel-inner">
                {% if bleach.product_set.all %}
				  {% for pro_img in bleach.product_set.all %}
					<div class="carousel-item {% if forloop.first %}active{% endif %}" data-bs-interval="1500">
						<img src="{{pro_img.Product_image.url}}" class="d-block img-fluid w-100 rounded" alt="unable load Image">
					</div>
				  {% endfor %}
				{% endif %}
				
              </div>
            </div>
          </div>
		  </a>
        </div>

{% endfor %}
      </div>
</section>

  <section class="featured_products">
    <h2 class="text-center text-capitalize m-5 ">Our Featured Products</h2>
    <div class="container px-lg-4">
      <div class="row gx-3 gx-lg-4 gy-4 justify-content-center">


	{%for featured_product in featured_products %}
        <div class="col-12 col-md-4 col-lg-3  p-0 featured_product_box ">
          <div class="featured_product_item overflow-hidden">
            <a href="{{featured_product.product_url}}">
              <div class="featured_product_img ">
                <img src="{{featured_product.Product_image.url}}" alt="" class="img-fluid">
              </div>
              <div class="about_featured_product alet alert-light p-1 text-center text-dark">
                <p class='fw-bold'>{{featured_product.product_name}}</p>
              </div>
            </a>
          </div>
        </div>
	{% endfor %}

      </div>
    </div>
  </section>


  <div class="section mx-auto mt-5">
    <div class="container overflow-hidden">
      <div class="note">
        {% comment %} <h4><b>Note :- </b>GloWhite Herbals Products are 100% natural and free from harmful chemicals.</h4> {% endcomment %}
      </div>
    </div>
  </div>


{% endblock content %}