core/urls.py
from django.urls import path
from.import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about-company/', views.about_Company, name='about-company'),
]

glowhiteherbals/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve


admin.site.site_header  =  "GloWhite Herbals Admin Panel"  
admin.site.site_title  =  "GloWhiteHerbals"
admin.site.index_title  =  ""
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('store/',include('store.urls')),
    path('accounts/',include('accounts.urls')),
    re_path (r'^media/(?P<path>.*)$', serve ,{'document_root' : settings.MEDIA_ROOT } ) ,
    
]
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

category/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    category_name        = models.CharField(max_length=255, unique=True)
    slug                 = models.SlugField(max_length=255, unique=True) 
    category_tagline     = models.CharField(max_length=350, blank=True, null=True)
    category_short_intro = models.CharField(max_length=350, blank=True, null=True)
    description          = models.TextField(blank=True, null=True)
    image1               = models.ImageField(upload_to='photos/category', blank=True, null=True)
    image2               = models.ImageField(upload_to='photos/category', blank=True, null=True)
    image3               = models.ImageField(upload_to='photos/category', blank=True, null=True)
    image4               = models.ImageField(upload_to='photos/category', blank=True, null=True)
    image5               = models.ImageField(upload_to='photos/category', blank=True, null=True)
    created_date         = models.DateTimeField(auto_now_add=True)
    modified_date        = models.DateTimeField(auto_now=True)
    def __str__(self):
        return str(self.category_name)

    class Meta:
        verbose_name_plural = 'Categories'

class SubCategory(models.Model):
    category_name    = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    subCategory_name = models.CharField(max_length=255, unique=True, blank=True, null=True)
    slug             = models.SlugField(max_length=255, unique=True, blank=True, null=True)   

    def __str__(self):
        return self.subCategory_name

    class Meta:
        verbose_name_plural = 'Sub Categories'
   
    def subcategory_url(self):
        return reverse('products_by_subcategory',args=[self.category_name.slug, self.slug])

core/models.py
from django.db import models
from PIL import Image

# Create your models here.
class Carousel(models.Model):
    carousel_title       = models.CharField(max_length=255, blank=True, null=True)
    carousel_description = models.TextField(blank=True, null=True)
    carousel_image       = models.ImageField(upload_to='photos/carouselImage')
    

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        imag = Image.open(self.carousel_image.path)
        output_size = (1280, 720,)
        newSize = imag.resize(output_size,Image.BICUBIC)
        newSize.format = 'PNG'
        newSize.save(self.carousel_image.path,quality=95)

    def __str__(self):
        return str(self.carousel_title)
    class Meta:
        verbose_name_plural = 'Sliders'

    

core/views.py
from django.http.response import HttpResponse
from django.shortcuts import render
from .models import Carousel
from category.models import Category
from store.models import Product
# Create your views here.

def home(request):
    carousel = Carousel.objects.all().order_by('-id')
    facial_kits = Category.objects.filter(category_name__icontains = 'facial kits')
    bleaches = Category.objects.filter(category_name__icontains = 'bleaches')

    featured_products = Product.objects.all().order_by('modified_date')[1::5]
    context={
        'carousel':carousel,
        'facial_kits':facial_kits,
        'bleaches':bleaches,
        'featured_products':featured_products,
    }
    return render(request, 'core/home.html',context)


def about_Company(request):
    return render(request, 'core/about.html')

core/templates/core/includes/footer.html
{% load static %}
<footer class="bg-secondary bg-dark mt-3 overflow-hidden footer">
    <div class="container p-0">
      <div class="social d-flex justify-content-center p-3">
       
        <div class="social_icon">
        <a href="https://www.instagram.com/glowhiteherbals/" target='blank_'><img src="{% static 'core/images/instagram.png' %}" alt="" class="img-fluid"></a>
        </div>
        <div class="social_icon">
          <a href="https://www.facebook.com/GloWhiteHerbals/"><img src="{% static 'core/images/SVG/facebook.svg' %}" alt="" class="img-fluid"></a>
        </div>
      </div>

      <div class="row gx-1 text-center text-white">

        <div class="col-6 colmd-6 col-lg-4">
          <h5>About Company</h5>
          <ul>
            <li class=text-center>GloWhite Herbals Based in Kolkata, it was Established in 1997, as a Salon Eco Products
              Manufacturer <br><a href="{% url 'about-company' %}" class="text-info ">read more</a></li>
          </ul>
        </div>
        <div class="col-6 colmd-6 col-lg-4">
          <h5>Products</h5>
          <ul>
          {% for category in links|slice:":3"%}
            <li class=text-center><a href="{% url 'products_by_category' category.slug %}" class="text-capitalize">{{category.category_name}}</a></li>
        {% endfor %}
            <li class=text-center><a href="{% url 'store' %}" class="text-info">View all</a></li>
          </ul>
        </div>
        <div class="col-6 colmd-6 col-lg-4">
          <h5>Get In Touch</h5>
          <ul>
            <li class=text-center><a href="{% url 'contac_us' %}">Contact Us</a></li>
            <li class=text-center><a href="mailto:amaan77866@gmail.com">Info@glowhiteherbals.com</a></li>
           
          </ul>
        </div>
      </div>
        <div class="footer-bottom">
          <p class='text-center fs-5'> © 2021 GloWhite Herbals</p>
        </div>
    </div>
    
  </footer>

core/templates/core/includes/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light shadow">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}"
      ><img src="{% static 'core/images/logo.png' %}" alt="" class="img-fluid"
    /></a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbar_id"
      aria-controls="navbar_id"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar_id">
      <ul class="navbar-nav m-auto">
        {% for category in links %} {% if category.subcategory_set.all %}

        <div class="dropdown">
          <li
            class="border-0 nav-link dropdown-toggle nav-item"
            type="button"
            id="dropdownMenuButton1"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            <a href="">{{category.category_name}}</a>
          </li>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            {% for subcategory in category.subcategory_set.all %}
            <li>
              <a
                class="dropdown-item nav-link text-capitalize"
                href="{{subcategory.subcategory_url}}"
                >{{subcategory.subCategory_name}}</a
              >
            </li>
            {% endfor %}
          </ul>
        </div>
        {% else %}
        <li class="nav-item">
          <a
            class="nav-link"
            aria-current="page"
            href="{% url 'products_by_category' category.slug %}"
            >{{category.category_name}}</a
          >
        </li>
        {% endif %} {% endfor %}

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           {% if request.user.is_authenticated %}
            <span class='text-warning'>{{request.user.username|slice:':7'}}..</span>
            {% else %}
            <span class='text-warning'>Accounts</span>
             
            {% endif %}

          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% if not request.user.is_authenticated %}
            <li><a class="dropdown-item" href="{% url 'user_registration' %}">Register</a></li>
            <li><a class="dropdown-item" href="{% url 'login' %}">Login</a></li>
            {% else %}
            <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
            {% endif %}
          </ul>
        </li>
       

      </ul>
    </div>
    <form action="{% url 'search' %}" method="GET" class="search-form">
      <div class="search-box">
        <input
          type="search"
          class="search-input"
          placeholder="Search on GLoWhite Herbals"
          name="keyword"
        />
        <div class="search-btn">
          
        </div> 
      </div>
    </form>
  </div>
</nav>